# Generated by Django 4.2.4 on 2023-09-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('titulo', models.CharField(max_length=60)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.TextField(max_length=250, null=True)),
                ('video', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriadorCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('foto_perfil', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('foto_perfil', models.TextField(max_length=250, null=True)),
                ('usuario', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=60)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campanha')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doador')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('numero', models.IntegerField()),
                ('validade', models.DateTimeField()),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doador')),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criadorcampanha'),
        ),
    ]
